site_name: Juan Florez
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags


markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition

nav:
  - Home: 'index.md'
  - Long read:
      - long-read/index.md
      - Runtime Map : long-read/map-graph.md
      - Planets : long-read/planets-bgr.md
  - About: 'about/index.md'
